collections:
  authors:
    output: true

url: "https://robyyx.github.io"
baseUrl: "/JekyllProject"

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
